@startuml "catalogo_estado"
left to right direction
skinparam roundcorner 5
skinparam linetype ortho
skinparam shadowing false
skinparam handwritten false
skinparam class {
 BackgroundColor white
 ArrowColor #2688d4
 BorderColor #2688d4
}

!define primary_key(x) <b><color:#b8861b><&key></color> x</b>
!define foreign_key(x) <color:#aaaaaa><&key></color> x
!define column(x) <color:#efefef><&media-record></color> x
!define table(x) entity x << (T, white) >>

package camara {
    table( catalogo_estado ) { 
    column ( id_estado ): int4
    column ( estado ): varchar(180
    column ( usuario_creacion ): varchar(6)
    column ( fecha_creacion ): timestamp
    column ( usuario_ultima_modificacion ): varchar(6)
    column ( fecha_ultima_modificacion ): timestamp
    column ( numero_tarea ): varchar(10)
    column ( sucursal ): varchar(3)
    column ( CONSTRAINT ): proceso_archivo_estado_key
    primary_key ( CONSTRAINT ): proceso_archivo_estado_pkey
    }
}

@enduml
